name: Deploy
on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Cache data
      uses: actions/cache@v2
      env:
        cache-name: cache-data
      with:
        path: ./data
        key: ${{ runner.os }}-deploy-${{ env.cache-name }}

    - run: npm ci
    - run: npm run run

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: data
