name: Deploy
on:
  push:
    branches: [ deploy ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Restore cache
      uses: actions/cache/restore@v4
      env:
        cache-name: cache_data
      with:
        path: ./data
        key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ github.run_id }}-${{ github.run_attempt }}
        restore-keys: |
          ${{ runner.os }}-deploy-${{ env.cache-name }}

    - name: Install
      run: npm ci

    - name: Run
      run: npm run run
      continue-on-error: true

    - name: Save cache
      uses: actions/cache/save@v4
      if: always()
      env:
        cache-name: cache_data
      with:
        path: ./data
        key: ${{ runner.os }}-deploy-${{ env.cache-name }}-${{ github.run_id }}-${{ github.run_attempt }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: data
